# Generated by Django 4.2.11 on 2025-05-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_traffic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadsegment',
            name='name',
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='length',
            field=models.FloatField(),
        ),
    ]
