# Generated by Django 4.2.11 on 2025-05-04 17:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('road_traffic', '0002_remove_roadsegment_name_roadsegment_speed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='reading',
            name='average_speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trafficintensityrange',
            name='max_speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trafficintensityrange',
            name='min_speed',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='VehiclePassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='road_traffic.car')),
                ('road_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='road_traffic.roadsegment')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='road_traffic.sensor')),
            ],
        ),
    ]
