# Generated by Django 4.2.11 on 2025-05-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_traffic', '0003_car_sensor_alter_reading_average_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
