# Generated by Django 4.2.11 on 2025-05-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_traffic', '0004_alter_reading_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsegment',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
